encoding: UTF-8
# Name of website
title: Python Sneks Curriculum

# Short description of your site
description: Introductory materials for Python

# Your name to show in the footer
author: Austin Cory Bart <acbart@udel.edu>
